openapi: 3.0.1
info:
  title: URL Shortener
  description: URL Shortening API - Coded in Kotlin - Powered by Micronaut
paths:
  /uba/tdl/metrics:
    get:
      tags:
      - URL Operations
      operationId: getMetrics
      parameters: []
      responses:
        "200":
          description: getMetrics 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/URLMetrics'
  /uba/tdl/redirect:
    get:
      tags:
      - URL Operations
      operationId: redirectURL
      parameters: []
      responses:
        "200":
          description: redirectURL 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
  /uba/tdl/shorten:
    post:
      tags:
      - URL Operations
      operationId: shortenURL
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LongURL'
        required: true
      responses:
        "200":
          description: shortenURL 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/URL'
components:
  schemas:
    ApiResponse:
      required:
      - message
      type: object
      properties:
        message:
          type: string
    LongURL:
      required:
      - url
      type: object
      properties:
        url:
          type: string
    URL:
      required:
      - hash
      - lastUsed
      - timesUsed
      - url
      type: object
      properties:
        url:
          minLength: 1
          type: string
        hash:
          minLength: 1
          type: string
        timesUsed:
          minimum: 0
          type: integer
          format: int32
        lastUsed:
          type: string
          format: date-time
    URLMetrics:
      required:
      - hash
      - lastUsage
      - originalDomain
      - usageCount
      type: object
      properties:
        originalDomain:
          type: string
        hash:
          type: string
        usageCount:
          type: integer
          format: int32
        lastUsage:
          type: string
          format: date-time
