micronaut:

  application:
    name: urlShortener

  server:
    port: ${PORT:8080}
    cors:
      enabled: true

    http:
        client:
            read-timeout: 20s

netty:
  default:
    allocator:
      max-order: 3

db:
  name: 'urlshort'
  collection: 'hashes'