micronaut:
    application:
        name: urlShortener
    http:
        client:
            read-timeout: 20s

netty:
    default:
        allocator:
            max-order: 3

db:
    name: 'urlshort'
    collection: 'hashes'